[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && bun run start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
serviceType = "web"
rootDirectory = "backend"
